# Generated by Django 5.1.6 on 2025-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel1',
            fields=[
                ('sign', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Na', max_length=30)),
                ('username', models.CharField(default='Na', max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
